#!/usr/bin/env node
// vim:ft=javascript

var soapController = require("./index.js"),
    express = require("express"),
    server = express.createServer();

// if not root, use dummy config required by test script
// otherwise, parse config from command-line arguments
var config = module.parent ? { port: 9876, soapUrl: "http://localhost:15099", prefix: "api" } :
             require('commander')
               .option("-v, --verbose", "Enable extensive logs")
               .option("-p, --port <port>", "Listening port")
               .option("-u, --soap-url <url>", "SOAP server url")
               .option("-P, --prefix <prefix>", "Url prefix. Defaults to none", "")
               .parse(process.argv);

if (!config.port || !config.soapUrl) {
   console.log("\n  Missing one or more <required> options!");
   console.log(config.helpInformation());
   process.exit(1);
}

// our catcher for log messages
process.addListener('uncaughtException', function (err, stack) {
   var message = 'Caught exception: ' + err;
   console.log(message);
});

if (config.verbose)
   server.use(express.logger({ format: '\x1b[1m:method\x1b[0m :url\x1b[0m :response-time ms\x1b[0m :status' }));

soapController.configure(server, config.soapUrl, config.prefix);

console.log("Using SOAP server on: ", config.soapUrl);
console.log("Listening on port: ", config.port);
if (config.prefix !== "")
   console.log("Service urls use prefix: ", config.prefix);
console.log();

server.listen(config.port);
